server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: goaly-api

  datasource:
    url: jdbc:postgresql://localhost:5432/goaltracker
    username: ${DB_USERNAME:goaltracker_user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    com.goaly.backend: DEBUG
    org.springframework.web: DEBUG
